default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: events_app
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>

development:
  <<: *default
  adapter: postgresql
  database: postgres
  host: localhost
  port: 5432
  username: postgres
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %> 

test:
  <<: *default
  adapter: postgresql
  database: postgres
  username: postgres
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %> 

production:
  adapter: postgresql
  database: postgres
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DATABASE_POOL_SIZE'] || 10 %>